flaskProyectMVC/models/albumModels.py
from app import mysql

# metodo para obtener albumes activos
def get_all():
    cursor = mysql.connection.cursor()
    cursor.execute('SELECT * FROM tb_album WHERE state = 1')
    consulta_todo = cursor.fetchall()
    cursor.close()
    return consulta_todo

# Obtener álbum por ID
def get_by_id(id):
    cursor = mysql.connection.cursor()
    cursor.execute('SELECT * FROM tb_album WHERE id = %s', (id,))
    result = cursor.fetchone()
    cursor.close()
    return result

# Insertar nuevo álbum
def insert_album(titulo, artista, anio):
    cursor = mysql.connection.cursor()
    cursor.execute(
        'INSERT INTO tb_album (album, artista, anio) VALUES (%s, %s, %s)',
        (titulo, artista, anio)
    )
    mysql.connection.commit()
    cursor.close()

# Metodo para actualizar un álbum
def update_album(id, album, artista, anio_int):
    cursor = mysql.connection.cursor()
    cursor.execute(
        '''
        UPDATE tb_album
        SET album = %s, artista = %s, anio = %s
        WHERE id = %s
        ''',
        (album, artista, anio_int, id)
    )
    mysql.connection.commit()
    cursor.close()

# Eliminar (soft delete)
def soft_delete(id):
    cursor = mysql.connection.cursor()
    cursor.execute('UPDATE tb_album SET state = 0 WHERE id = %s', (id,))
    mysql.connection.commit()
    cursor.close()

flaskProyectMVC/app.py
from flask import Flask,jsonify
from flask_mysqldb import MySQL
import MySQLdb
from config import Config


mysql = MySQL()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    mysql.init_app(app)
    
    from controllers.albumController import albumsBP
    app.register_blueprint(albumsBP)
    
    return app

#ruta para probar la conección a mysql
'''@app.route('/DBCheck')
def DB_check():
    try:
        cursor= mysql.connection.cursor()   
        cursor.execute('Select 1')
        return jsonify( {'status':'ok','message':'Conectado con exito'} ), 200
    except MySQLdb.MySQLError as e:
        return jsonify( {'status':'error','message':str(e)} ), 200


@app.route('/consulta')
def consulta():
    return render_template('consulta.html')'''

if __name__ == '__main__':
    app = create_app()
    app.run(port=3000, debug=True)

flaskProyectMVC/controllers/albumController.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.albumModels import *

albumsBP = Blueprint('albums', __name__)

@albumsBP.route('/')
def home():
    try:
        consulta_todo = get_all() #FUNCIÓN DE OBTENER ALBUMES
        return render_template('formulario.html', errores={}, albums=consulta_todo)
    except Exception as e:
        print('Error al consultar todo: ' + str(e))
        return render_template('formulario.html', errores={}, albums=[])

@albumsBP.route('/detalle/<int:id>')
def detalle(id):
    try:
        consulta_id = get_by_id(id) #FUNCION PARA OBTENER ALBUM POR ID
        return render_template('consulta.html', album=consulta_id)
    except Exception as e:
        flash('Error al consultar el álbum: ' + str(e))
        return redirect(url_for('albums.home'))

@albumsBP.route('/guardarAlbum', methods=['POST'])
def guardar():
    errores = {}
    titulo = request.form.get('txtTitulo', '').strip()
    artista = request.form.get('txtArtista', '').strip()
    anio = request.form.get('txtAnio', '').strip()

    if not titulo:
        errores['txtTitulo'] = 'Nombre del álbum obligatorio'
    if not artista:
        errores['txtArtista'] = 'Artista obligatorio'
    if not anio:
        errores['txtAnio'] = 'Año obligatorio'
    elif not anio.isdigit() or int(anio) < 1800 or int(anio) > 2100:
        errores['txtAnio'] = 'Ingresa un año válido'

    if errores:
        return render_template('formulario.html', errores=errores, albums=get_all())

    try:
        insert_album(titulo, artista, anio) #FUNCION DE INSERTAR ALBUM
        flash('Álbum guardado en la BD')
        return redirect(url_for('albums.home'))
    except Exception as e:
        flash('Error al guardar: ' + str(e))
        return redirect(url_for('albums.home'))

@albumsBP.route('/editar/<int:id>')
def editar(id):
    album = get_by_id(id) #FUNCION PARA OBTENER ALBUM POR ID REUTILIZADA
    
    if album is None:
        flash('Álbum no encontrado')
        return redirect(url_for('albums.home')) 
    
    return render_template('formUpdates.html', album=album)

@albumsBP.route('/actualizar/<int:id>', methods=['POST'])
def actualizar(id):
    # 1. Recoger datos del formulario
    album = request.form.get('txtTitulo', '').strip()
    artista = request.form.get('txtArtista', '').strip()
    anio = request.form.get('txtAnio', '').strip()

    # 2. Validar datos
    errores = {}

    if not album:
        errores['txtTitulo'] = 'El título del álbum es obligatorio'
    if not artista:
        errores['txtArtista'] = 'El artista es obligatorio'
    if not anio:
        errores['txtAnio'] = 'El Año es obligatorio'
    else:
        try:
            anio_int = int(anio)
            if anio_int < 1800 or anio_int > 2030:
                errores['TxtAnio'] = 'Ingresa un año válido (entre 1800 y 2030)'
        except ValueError:
            errores['TxtAnio'] = 'El año debe ser un número válido'

    if errores:
        album_data= get_by_id(id) #REUTILIZACIÓN DE GET BY ID
        return render_template('formUpdate.html', album=album_data, errores=errores)

    try:
        update_album(id, album, artista, anio_int)
        flash('Álbum actualizado en la BD')
    except Exception as e:
        mysql.connection.rollback()
        flash(f'Error al actualizar: {str(e)}', 'danger')

    return redirect(url_for('albums.home'))

@albumsBP.route('/eliminar/<int:id>', methods=['POST'])
def eliminar(id):
    try:
        soft_delete(id)
        flash('Álbum eliminado correctamente')
    except Exception as e:
        print('Error al eliminar el álbum: ' + str(e))
        flash('Error al eliminar el álbum')
    return redirect(url_for('albums.home'))    

@albumsBP.route('/confirmar_eliminar/<int:id>')
def confirmar_eliminar(id):
    try:
        album = get_by_id(id) #SE VUELVE A REUTILIZAR EL FETCHONE
        if album is None:
            flash("Álbum no encontrado")
            return redirect(url_for('home'))
        return render_template('confirmDel.html', album=album)
    except Exception as e:
        print('Error al cargar confirmación: ' + str(e))
        flash("Error al intentar eliminar")
    return redirect(url_for('albums.home'))

flaskProyectMVC/templates/confirmDel.html
{% extends 'plantilla.html' %}

{% block body %}
<div class="row m-1">
    <div class="col-10 offset-1 col-md-8 offset-md-2">
        <h2 class="display-5 mt-5 mb-4 text-primary">Confirmar Eliminación</h2>

        <h4 class="text-danger mb-4">¿Estás seguro de que quieres eliminar este álbum?</h4>

        <div class="table-responsive">
            <table class="table table-bordered table-hover text-start">
                <thead class="table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Título</th>
                        <th>Artista</th>
                        <th>Año</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ album.0 }}</td>
                        <td>{{ album.1 }}</td>
                        <td>{{ album.2 }}</td>
                        <td>{{ album.3 }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <form action="{{ url_for('albums.eliminar', id=album.0) }}" method="post" class="mt-4 d-flex gap-3">
            <button type="submit" class="btn btn-danger">Sí, eliminar</button>
            <a href="{{ url_for('albums.home') }}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

flaskProyectMVC/templates/consulta.html
{% extends 'plantilla.html' %}

{% block body %}
<div class="row m-1">
    <div class="col-12">
        <h2 class="display-4 mt-5 mb-5 titulo">Vista de Consulta</h2>
        <a href="/" class="mx-3">Regresar al Formulario</a>

        <div class="table-responsive mt-4 ms-3" style="max-width: 100%;">
            <table class="table table-striped table-hover text-start align-middle w-auto">
                <thead class="table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Álbum</th>
                        <th>Artista</th>
                        <th>Año de Publicación</th>
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ album.0 }}</td>
                        <td>{{ album.1 }}</td>
                        <td>{{ album.2 }}</td>
                        <td>{{ album.3 }}</td>
                        <td><a class="btn btn-warning btn-sm" href="/editar/{{ album.0 }}">Actualizar</a></td>
                        <td><a class="btn btn-danger btn-sm" href="/confirmar_eliminar/{{ album.0 }}">Eliminar</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

flaskProyectMVC/templates/formUpdates.html
{% extends 'plantilla.html' %}

{% block body %}
<div class="row m-1">
    <div class="col-10 offset-1 col-md-6 offset-md-3">
        <h2 class="display-5 mt-5 mb-4 text-success">Actualizar Álbum</h2>

        <form action="{{ url_for('albums.actualizar', id=album.0) }}" method="post" class="form-transparent shadow-lg p-4 rounded bg-wray">
            <div class="mb-3">
                <input type="text" class="form-control text-black form" name="txtTitulo" placeholder="Título" value="{{ album.1 }}">
                {% if errores and 'txtTitulo' in errores %}
                    <p class="text-danger">{{ errores['txtTitulo'] }}</p>
                {% endif %}
            </div>

            <div class="mb-3">
                <input type="text" class="form-control text-black" name="txtArtista" placeholder="Artista" value="{{ album.2 }}">
                {% if errores and 'txtArtista' in errores %}
                    <p class="text-danger">{{ errores['txtArtista'] }}</p>
                {% endif %}
            </div>

            <div class="mb-3">
                <input type="number" class="form-control text-black" name="txtAnio" placeholder="Año de publicación" value="{{ album.3 }}">
                {% if errores and 'txtAnio' in errores %}
                    <p class="text-danger">{{ errores['txtAnio'] }}</p>
                {% endif %}
            </div>

            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary">Actualizar Álbum</button>
            </div>
        </form>

        <div class="mt-3">
            <a href="/" class="btn btn-secondary">Cancelar</a>
        </div>
    </div>
</div>
{% endblock %}

flaskProyectMVC/templates/formulario.html
{%extends 'plantilla.html'%}

{%block body%}

<div class="row m-1">
    <div class="col-6 form-container">
        <h2 class="display-4 mt-5 mb-5 titulo"> Vista de formulario</h2>
        <a href="/consulta" class="mx-3"> Abrir Vista Consulta</a>

        {% with mensajes= get_flashed_messages()%}
            {% if mensajes%}
                {% for msj in mensajes%}
                    <h4>{{ msj }}</h4>
                {% endfor %}
            {% endif %}
        {% endwith%}

        <form action="/guardarAlbum" method="post" class="form-transparent shadow-lg">
            <div class="mb-3">
                <input type="text" class="form-control" name="txtTitulo" placeholder="Titulo" value="{{ request.form.txtTitulo}}">
                {% if errores and errores.txtTitulo %}
                <p style="color:red">{{ errores.txtTitulo }}</p>
                {% endif %}
            </div>

            <div class="mb-3">
                <input type="text" class="form-control" name="txtArtista" placeholder="Artista" value="{{ request.form.txtArtista}}">
                {% if errores and errores.txtArtista %}
                <p style="color:red">{{ errores.txtArtista }}</p>
                {% endif %}
            </div>

            <div class="mb-3">
                <input type="number" class="form-control" name="txtAnio" placeholder="Año de publicación" value="{{ request.form.txtAnio}}">
                {% if errores and errores.txtAnio %}
                <p style="color:red">{{ errores.txtAnio }}</p>
                {% endif %}
            </div>

            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-success">Guardar Álbum</button>
            </div>
        </form>


    </div> <!-- columna de 5-->

    <div class="col-6 list-container">
        <h2 class="titulo mt-5 ms-3">Albums Guardados</h2>
        <div class="table-responsive ms-3" style="max-width: 100%;">
            <table class="table table-striped table-hover text-start align-middle w-auto">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Álbum</th>
                    </tr>
                </thead>
                <tbody>
                    {% for alb in albums %}
                    <tr>
                        <td>{{ alb.0 }}</td>
                        <td><a href="/detalle/{{ alb.0 }}">{{ alb.1 }}</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    
</div><!--cierre del row-->
{%endblock%}

flaskProyectMVC/templates/plantilla.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plantilla</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='CSS/styles.css') }}">

</head>

<body>
    {%block body%}
    
    {%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>